import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
import { API_PARAMS } from '../api-params'

export const autoGeneratedBaseApi = createApi({
  reducerPath: 'autoGeneratedBaseApi',
  baseQuery: fetchBaseQuery(API_PARAMS),
  endpoints: () => ({}),
})
