import { configureStore, Middleware } from '@reduxjs/toolkit'
import { autoGeneratedBaseApi } from './api/auto-generated/auto-generated-base.api'
import userReducer from '../lib/reducers/userSlice'

export const errorsHandler: Middleware = () => (next) => (action) => {
  // unauthorized
  if (401 == action?.payload?.status) {
    window.location.href = '/auth/login'
    return
  }

  if (403 == action?.payload?.status) {
    // eslint-disable-next-line no-alert
    alert('Permission denied')
    return next(action)
  }

  return next(action)
}

export const store = configureStore({
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware()
      .concat(autoGeneratedBaseApi.middleware)
      .concat(errorsHandler),
  reducer: {
    userReducer,
    [autoGeneratedBaseApi.reducerPath]: autoGeneratedBaseApi.reducer,
  },
})

export type RootState = ReturnType<typeof store.getState>

export type AppStore = typeof store
