name: CI

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 origin master
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm tsc
      - run: pnpm lint
      - run: pnpm lint-styles
      - run: pnpm prisma validate
      - run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'pnpm'
      - run: pnpm install --ignore-scripts --frozen-lockfile
      - run: pnpm build
